package: export_cleanup
version: '0.2'
author: 'Friends Of REDAXO'
supportpage: www.redaxo.org/de/forum/

requires:
    packages:
        backup: '^2.0.3'
        cronjob: '^2.1.0'
    redaxo: '^5.1.0'
